### ISSUE TITLE
Is there trigger test?

### ISSUE THREAD

**Issue by yepYoung** [sola-st/PyTy#2]
Hi，I’ve heard so much about this great paper！But I can't find the trigger test for this very nice dataset，is there trigger test？
Can you give me some details?
Thank you so much！

**Comment by luca-digrazia** [comment]
Hi,

Thank you so much for your interest in the paper and the dataset. Could you please provide an example of the trigger test you are looking for?

Thanks.

**Comment by yepYoung** [comment]
Hi，Thank you for your reply！
Just like this：https://github.com/kupl/PyTER/blob/main/bugsinpy_info/fastapi-1/tests/test_jsonable_encoder.py
The test function that can pick the plausible patches.

**Comment by luca-digrazia** [comment]
Hi,

You can check the folder: `https://github.com/sola-st/PyTy/blob/main/src/eval_code/`

For example the file: `https://github.com/sola-st/PyTy/blob/main/src/eval_code/eval_pyty_testing.py`
should do what you ask. Let me know, if you have questions.
